### ISSUE TITLE
example configurations

### ISSUE THREAD

**Issue by zonca** [jupyterhub/batchspawner#12]
I would like to add the setup I use on Comet at SDSC as an example of interfacing with SLURM remotely via `gsissh`/`ssh`.

What is the best place to put them? 

some ideas:

* wiki
* folder in the repository
* standalone repository linked in the wiki
* gist

Moreover, my setup is also integrated with a OAUTH service with `oauthenticator`, is it confusing if I add also this to the mix or better just share the `batchspawner` configuration?

**Comment by mbmilligan** [comment]
Hi Andrea! @minrk and I were discussing the other day creating another repo under the Jupyterhub org, maybe call it jupyterhub-deploy-hpc, to document a reference deployment alongside the docker and nbgrader examples. I think, since there's so much variability possible, it would be more useful to have a small collection of high quality examples. 

Here's what I propose:

1. I'll create a new repo, jupyterhub-deploy-hpc
2. In parallel, you, and I, and whoever else wants to, create a personal repo containing a worked and documented example.
3. Each example will get a corresponding branch in the main repo and can submit changes to that branch with a PR.

How's that sound?

**Comment by zonca** [comment]
Branches are not very visible, why don't we use folders?

**Comment by minrk** [comment]
Folders sounds good to me - it's more easily navigable that way.

**Comment by mbmilligan** [comment]
Okay, the masses have spoken -- folders it is.

I've created https://github.com/jupyterhub/jupyterhub-deploy-hpc -- please send content via PR.

Let's create folders by site (e.g. I'll call mine UMN-MSI, maybe @zonca can call his SDSC) and in README.md add a line linking to the folder with a brief description. If that naming scheme proves unwieldy we can always move things around later.
