### ISSUE TITLE
jupyterhub install needed on nodes?

### ISSUE THREAD

**Issue by andreas-h** [jupyterhub/batchspawner#23]
Just a question, because this is not explicitly mentioned:

When using `SlurmSpawner` to run notebooks the compute nodes of our cluster, does *jupyterhub* need to be installed on each compute node?  The command `jupyterhub-singleuser` which is run in all the example job scripts seems to imply this.

If this is indeed the case, is there any way around this?  The notebook is installed on the compute nodes, but currently I only have Python2.7 there, and jupyterhub requires 3.x ...

**Comment by mbmilligan** [comment]
Hi,

The Jupyterhub singleuser app does need to be installed on the compute
nodes - the Notebook app on its own doesn't have the necessary logic to
communicate with the Hub. I'm not aware that anyone has made a Python 2
version of those bits, although it probably wouldn't be too hard.

That said, you just need to be able to install the Jupyterhub and Notebook
apps under Python 3 - your kernels with whatever software stack you need
can be in any language that supports a Jupyter kernel. I've solved this
problem in the past (managed CentOS 6 system with no installed Python 3) by
deploying a small Miniconda environment that contains only Jupyterhub,
Notebook, and their dependencies. That can be quite small and runs fine
from user-managed space.

Regards,
Michael


On Dec 27, 2016 7:45 AM, "Andreas Hilboll" <notifications@github.com> wrote:

Just a question, because this is not explicitly mentioned:

When using SlurmSpawner to run notebooks the compute nodes of our cluster,
does *jupyterhub* need to be installed on each compute node? The command
jupyterhub-singleuser which is run in all the example job scripts seems to
imply this.

If this is indeed the case, is there any way around this? The notebook is
installed on the compute nodes, but currently I only have Python2.7 there,
and jupyterhub requires 3.x ...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyterhub/batchspawner/issues/23>, or mute the thread

**Comment by andreas-h** [comment]
thanks, Michael, that's exactly what I did now (use miniconda3).
