### ISSUE TITLE
Any way to not have public notebook servers?

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/batchspawner#31]
Hello, I'm looking to use Jupyter on our cluster. My one concern is that of public notebooks. From looking at the code it appears the hub submits a job to a node machine. This starts a notebook that must be accessible from the hub. The hub then gets the hostname and uses that as the IP to proxy the user to their server. This means that jupyter binds to the public IP of the node machine.

In our case, our node machines are internet accessible, meaning that the notebook servers would be accessible outside the hub. This raises 2 concerns:

1. Unauthorized access
2. Encryption between hub and node machine

I know the new jupyter token authentication introduced in 4.3.0 solves 1, but there is still no encryption between the hub and the node machines.

Is there any way to not have public notebooks? Somehow have it bind to `localhost` and tunnel the connection to the hub? While not a deal breaker, this would be nice.

**Comment by zonca** [comment]
I have setup batchspawner with SSH tunneling, see
https://zonca.github.io/2017/02/sample-deployment-jupyterhub-hpc.html

**Comment by mbmilligan** [comment]
Thanks @zonca - I was just going to suggest your work, thanks for the handy reference link too!

That said, let me add that leaving your cluster compute nodes fully visible to the public internet is not the greatest idea. Many computational tools besides Jupyter will open network ports and, since these sorts of tools are usually used in more controlled environments, the attention to security will be of widely varying quality. Personally, I would at minimum block inbound connections to all but essential services (usually just SSH on port 22) for addresses outside your network. 

I would also note that the above is probably a much more important security measure than encrypting traffic between the hub and node. Since the secret token is needed for the notebook processes to respond to connections, the only thing you are mitigating is the possibility that sensitive user data is intercepted in transit. However, if you have untrusted users able to sniff arbitrary traffic on your internal network, you probably have bigger problems than that.

**Comment by aseishas** [comment]
Internal encryption is a requirement in our environment, too, and we're looking at the recent changes made in https://github.com/jupyterhub/jupyterhub/issues/370 (https://github.com/jupyterhub/jupyterhub/pull/2055) to resolve item 2. Is it feasible for batchspawner to support end-to-end encryption this way?

**Comment by mbmilligan** [comment]
Ah, it's great to see that long-running PR finally resulted in a merge. Thanks for bringing that to our attention! I am still digesting the changes introduced there, but it should be doable to support. That said, given the diversity of batch systems and environments, I would expect that the batchspawner implementation will consist mainly of hooks to allow site admins to plug in their own behavior, especially in the case where they want to let Jupyterhub generate certs and stage them over to the compute nodes. We can probably provide some sensible default behavior if they just want to drop in a path to pre-generated host certificates though.

**Comment by DeepHorizons** [comment]
With the release of JupyertHub 1.0 having the PR for internal encryption I'm closing this issue
