### ISSUE TITLE
Job request request validation step

### ISSUE THREAD

**Issue by willfurnass** [jupyterhub/batchspawner#36]
Could be useful to quickly provide feedback in cases where a set of resource requests could never be satisfied, even with an empty cluster.

E.g. for Grid Engine:
1. run `qsub -w v <job spec here> for dry-run validation of the resource requests and if the return status is okay then
2. run `qsub <job spec here>

NB we've found that such validation mechanisms can sometimes return [false negatives](http://rse.shef.ac.uk/blog/sge-job-validation-2/).

**Comment by mbmilligan** [comment]
My suggestion here would be to use `batchspawner` in combination with the `ProfilesSpawner` from [wrapspawner](https://github.com/jupyterhub/wrapspawner), so that the administrator can pre-populate the form with job configurations that are known to work. If you want to perform validation on scripts with user-provided parameters, the simplest way to make that happen would be to call a shell script in place of `qsub`, which does the test you describe and exits with a non-zero exit code on failure. Unfortunately this will not provide a very friendly user experience, because we don't currently have a mechanism to pass error text back to the user. Creating such a user feedback mechanism would be a worthwhile effort, but that probably needs to happen in the Jupyterhub project, not here.
