### ISSUE TITLE
"spawner.ip" is not cleaned up when the SingleUserServer stops

### ISSUE THREAD

**Issue by gdlmx** [jupyterhub/batchspawner#76]
## Behavior

After a user start and stop the server multiple times using the `batchspawner`, the IP and port of the prior spawner are feed to the new spawner's arguments. It is shown in the logs that:

    [I 2018-04-29 12:58:18.960 JupyterHub batchspawner:186] Spawner submitted script:
    ...
    jupyter-labhub --ip=""<OLD_HOSTNAME>"" --port=<OLD_PORT> --notebook-dir=""~/"" --NotebookApp.default_url=""/lab"" --disable-user-config
    ...

If the batch system (HTCondor in my case) doesn't schedule the job to the same host as the last one, the single-user server will crash because it is told to bind to the wrong hostname/IP. 

## Reason

The `BatchSpawnerBase.stop()` doesn't clean up the `Spawner` object which is NOT destroyed after the single-user server stops.

https://github.com/jupyterhub/batchspawner/blob/846a900e2e330ed1056c60cf32cf39a50fc760da/batchspawner/batchspawner.py#L333

## Proposed solution

- Clean up the spawner at the beginning of `BatchSpawnerBase.start()` or in the `Spawner.pre_spawn_hook`.
- Do not reuse the spawner object.

**Comment by mbmilligan** [comment]
Hi, thanks for the report. You have discovered a significant regression. Since the cause is known, I will issue a release with a fix as soon as possible.

To be clear, the IP value substituted into the job script is not the address of the notebook server -- in fact it couldn't be, since the batch system doesn't decide where the job will run until after the script has been submitted. Instead, it is the address that the notebook server should listen on, normally set to "0.0.0.0" so the server listens on all available interfaces where it is running.

In d3766746174af006ce10bc437f1f0fb4261f248a the Spawner code was updated to avoid using the deprecated `self.user.server.ip` mechanism to communicate the IP address of the notebook server. Now that value is returned directly to the Hub, but we continued to use a class attribute as well, to support conditionally using the old behavior for old Jupyterhub versions. Unfortunately, I now see that the temporary attribute used clobbers the configured listen IP address. 

The result is that the first invocation will work correctly (clearly this is how it passed our testing for so long), but subsequently the listen address is set to the IP address where the *previous* notebook session ran.

Solution: use a different name than `self.ip` in the following section:

https://github.com/jupyterhub/batchspawner/blob/846a900e2e330ed1056c60cf32cf39a50fc760da/batchspawner/batchspawner.py#L320-L330
