### ISSUE TITLE
Batchspawner and PBS Pro 14.1.0

### ISSUE THREAD

**Issue by llgxela** [jupyterhub/batchspawner#79]
Hi,

Does anybody know if the TORQUE spawner is compatible with PBS Pro 14.1.0?
The basic syntax is pretty similar (if not identical).

Has anybody had success with it?

Thanks

**Comment by mbmilligan** [comment]
I can't find the source right now, but I recall hearing that someone was successful using the TorqueSpawner class with PBS Pro. They may have had to adjust the templates though. In particular it looks like PBSPro doesn't support the XML qstat output format that the current regexes expect, so you'd  have to adapt those.

**Comment by llgxela** [comment]
Thank you, I will definitely give it a try.

Thanks

**Comment by rkdarst** [comment]
Did this work?  If you find things that don't work and can describe what needs changing, I can take a look at it if you don't want to yourself.

**Comment by guillaumeeb** [comment]
Hi every one, `TorqueSpawner` is not really compatible with PBS versions above 13, and maybe before. It uses some old syntax, like `ppn` instead of `ncpus`. Some of this can be changed through configuration, but not all easily, like for example the qstat output difference mentionned above. 

I believe it would be much better if we could come up with and PBSSpawner class in addition to the TorqueSpawner one. They would be very close, but that could give a much reasonnable start for PBS clusters.

Any though about that? I could probably work on it and issue a PR.

**Comment by guillaumeeb** [comment]
Here is a simple config that works on my PBS Cluster for TorqueSpawner:
````python
c.TorqueSpawner.batch_script = '''#!/bin/sh
#PBS -N rt_algos
#PBS -l select=1:ncpus={nprocs}:mem={memory}
#PBS -l walltime={runtime}
#PBS -v {keepvars}

#echo $PBS_NODEFILE

module load conda
source activate jupyterhub

{cmd} --debug
'''

c.TorqueSpawner.batch_query_cmd = 'qstat -fx {job_id}'
c.TorqueSpawner.state_pending_re = r'job_state = [QH]'
c.TorqueSpawner.state_running_re = r'job_state = R'
c.TorqueSpawner.state_exechost_re = r'exec_host = ([\w_-]+)/'
````

Setting the regular expression in a default PBS configuration could be helpfull for other I believe. Not sure exec_host one is OK for everyone though. I propose to create a class that inherith TorqueSpawner, like what is done with Moab.

**Comment by rkdarst** [comment]
This looks good to me.  Will you make a pull request or should I?

I would say, instead of the `module load conda` and `source activate` lines, put in a `{prologue}` line which can then be set to custom pre/post start scripts easily.  There is a pull request waiting with this... adds some cheap generalization.

There's some more to improve, but it's waiting for some other PRs so we can wait for those.

**Comment by mbmilligan** [comment]
Agreed, this is exactly the sort of customization that Batchspawner's subclassing is intended to address. As mentioned above, site-specific lines like "module load..." should be kept out of the default scripts, and in general the default scripts should be as similar to each other as possible to minimize surprise for the site admin configuring it. If this gets put into a PR, and those issues are addressed, I think we'd be happy to accept it for the release we're starting to assemble.

**Comment by guillaumeeb** [comment]
I'll try to work on this PR, I may need help for testing the prologue thing. Should I start from the associated PR branch ?

**Comment by rkdarst** [comment]
It would probably be simplest to wait for the other branches to be accepted first... hint hint.  I'd say do what you can based on what is in batchspawner already, we can always do further refinements later.
