### ISSUE TITLE
Why is the implementation of `make_preexec_fn` not different from that in `Spawner`?

### ISSUE THREAD

**Issue by krinsman** [jupyterhub/batchspawner#83]
The (concrete) implementation of `make_preexec_fn` [in the `BatchSpawnerBase` class](https://github.com/jupyterhub/batchspawner/blob/master/batchspawner/batchspawner.py#L257) is, as far as I can tell, exactly the same as that of `make_preexec_fn` [in the `Spawner` class](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L1020), from which `BatchSpawnerBase` inherits.

Why is the method "overwritten" in `BatchSpawnerBase` if no concrete changes are made to the implementation? Is this for historical reasons (e.g. an earlier version of the `Spawner` superclass did not have that method)?

The docstrings between the two methods are different -- is that the reason for "overwriting" the version from the parent `Spawner` class?

**Comment by mbmilligan** [comment]
It's mostly cruft - iirc I included that function intending to provide an alternate `run_command` implementation that would use `setuid` instead of `sudo`, but nobody ever asked for that. Notice that the function you linked to is actually implemented in `LocalProcessSpawner`, not the base class, so it isn't in our inhertance chain here.

**Comment by krinsman** [comment]
You're right -- sorry about that. Thank you for your time and help!
